### ISSUE TITLE
browse paging sometimes goes haywire but only with surface geo queries

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#101]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/100

**Comment by rfrenchseti** [comment]
Not enough detail to reproduce.
