### ISSUE TITLE
Prevent browser reflow that happens when green numbers change

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#106]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

try a css min_width 

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/105

**Comment by rfrenchseti** [comment]
Any attempt to do this is going to require a minimum field length, which will make the widget larger than it needs to be. I don't think the reflow is a big deal.
