### ISSUE TITLE
closing the intented target tab leads to broken getHinting for other widgets

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#109]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

open Instrument Name tab and then close X the Intended Target Name tab, then start changing to different planets, the green numbers for Instrument widget will not function

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/108

**Comment by physicsguy42** [comment]
I don't see the issue. What is meant by, "the green numbers for Instrument widget will not function"? I opened opus then clicked on Instrument name. the "Instrument Name" widget opens successfully. I closed the "Intended Target Name" widget and the green numbers next to instrument names seem stable. However, if I pick a specific planet the number next to the instrument doesn't change. But if I constrain the data using a widget with a max and a min, like "observation time" the numbers next to the instrument names do change.
