### ISSUE TITLE
Detail page needs 'add to cart' button

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#110]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/109

**Comment by rfrenchseti** [comment]
Decided to do BYBTW 3/18/21. Combine with #790 and put the add to cart in the stationary header.
