### ISSUE TITLE
Add mechanism for short-term notifications

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#1115]
OPUS needs a mechanism to display a banner of some kind when people start OPUS, for announcements such as upcoming service interruptions. This would be done by reading a local file on the server, and, if it exists, displaying it in a pretty manner.

**Comment by dstopp** [comment]
Combine w/ api_last_blog_update to include the ability for the short term notification to appear.  
-Add a new parameter to opus_secrets in template that looks at another file that contains the notification details in text.  The front end will manage the html formatting of the details, if any, that come from the back end and throw up a splash page w/that information.
