### ISSUE TITLE
Previous scroll position isn't being maintained when returning to browse tab in table view

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#114]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/113

**Comment by physicsguy42** [comment]
This appears to still be an open issue

**Comment by rfrenchseti** [comment]
Scroll down on the gallery page. Switch to the Search tab. Switch back to the Browse Results tab. The scroll position has returned to the top.

**Comment by rfrenchseti** [comment]
This is actually still broken with the table view.
