### ISSUE TITLE
Social sharing from detail page picks up wrong image

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#117]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

sharing an image to Pinterest from detail page doesn't work, pinterest is picking up entire gallery, probably similar for facebook etc. 

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/116

**Comment by rfrenchseti** [comment]
I assume this means that if you try to copy-paste the URL into pinterest, you get the wrong image.

**Comment by rfrenchseti** [comment]
In Facebook there is no image, and pinterest says it can't find an image to use. I'm going to close this bug.
