### ISSUE TITLE
Clarify tooltip for Filter [Cassini ISS]

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#1178]
A user was confused that CL1 and CL2 were missing from Cassini ISS filter names. Clarify this in the tooltip.

**Comment by matthewtiscareno** [comment]
Here is some raw material for the tooltip, from an email I sent today to a user: 

For Cassini ISS, the filter “CL2” is a clear filter.  Therefore, when it is combined with another filter the effective result is that only the other filter is worth mentioning.  In our “Filter [Cassini ISS]” field, there is a checkbox that is labeled simply “UV2,” and this checkbox is the one that yields the filter combination you are seeking.  The link below shows all 2256 images that use this filter combination, and I’ve scrolled it to a point where a text search will reveal the specific image you mention. 
 
It is always a struggle to find a balance between supplying sufficient detail and avoiding unnecessary clutter in our display.  This is why the only mention of either the CL1 or CL2 filter in our “Filter [Cassini ISS]” field is when the two are combined, and that option is labeled “CLEAR.”

**Comment by rfrenchseti** [comment]
I suggest "When only one filter name is shown, the other is assumed to be either CL1 or CL2 as appropriate".

**Comment by matthewtiscareno** [comment]
Or perhaps “When only one filter name is shown, the other is assumed to be one of the clear filters (CL1 or CL2, as appropriate).”
