### ISSUE TITLE
new data import could be improved

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#118]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

when new data is imported to the database it results in destroying the old database and building a complete new one, but this is a lot of time and cpu cycles and database load and doesn't need to be this way, and might be getting in the way of other queries hitting the database. It would also be nice to be able to do incremental imports without this multi day process. 

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/117

**Comment by rfrenchseti** [comment]
The import pipeline needs to be completely rewritten to make it more streamlined and also support incremental volume updates for PDS4.

**Comment by rfrenchseti** [comment]
This is no longer relevant.
