### ISSUE TITLE
Cassini observations that do not have calibrated images produce strange manifest files

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#129]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

Manifest reports 'cannot find' and lists bunch of calibrated files for Cassini for obs that don't have calibrated files (like for Jupter) 

an artifact of the algorithm for finding Cassini files being too broad and thinks everything should have a calibrated file, an error which has been tolerable for backend updates but having it show to users in manifest file is not helpful. 

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/128

**Comment by basilleaf** [comment]
_Original comment by_ **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**:

---

please update line 82 in metrics/opus2_file_downloads_by_instrument.py when this is fixed

**Comment by rfrenchseti** [comment]
No longer an issue
