### ISSUE TITLE
Using Intended Target and Surface Geo Target at the same time is bad

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#13]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

solution: when user selects a surface target IF an intended target is also selected display a pop-up/modal to explain to them they are getting the intersection, and if they really want to search surface targets they should de-select the Intended target

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/11

**Comment by rfrenchseti** [comment]
This is the proper behavior and we will leave it as is.
