### ISSUE TITLE
Table headers partially disappear when scrolling from gallery view

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#133]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/132

**Comment by rfrenchseti** [comment]
Go to the Browse Results table, select View Table, and then scroll. The headers at the top of the table partially disappear.
