### ISSUE TITLE
metrics for API

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#137]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

want metrics for API guide page - hit counter for that page

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/136

**Comment by rfrenchseti** [comment]
We actually have this now through AWSTATS.
