### ISSUE TITLE
Add 'Add all to Cart' button on main gallery page

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#138]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

Mark and user Michael both requested this, quick and dirty benchmark says it's not as slow as I'd thought it would be! 

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/137

**Comment by basilleaf** [comment]
this is actually ready [on branch "builk_add"](https://github.com/basilleaf/opus/tree/bulk_add) but holding it until dev server is ready for testing it out on full production-sized database.

**Comment by basilleaf** [comment]
This is now merged into master, but is hidden in interface b/c needs more testing/limits and such. 

see: [0787e6da0fbe81e86](https://github.com/basilleaf/opus/commit/ff094a96ebaaf411c824f460787e6da0fbe81e86)

it's the edit_collection_addall() in user_collections

**Comment by basilleaf** [comment]
here is where the [feature was added](https://github.com/basilleaf/opus/commit/5219f5990a519534822452f9d57bf7371efd43f9)

**Comment by rfrenchseti** [comment]
This will need changes to the Django to permit efficient adding/removing all, efficient check of an image in the cart, and checks on download and CSV size.

**Comment by rfrenchseti** [comment]
addall is implemented in the API, but still needs to be invoked by a button on the browse tab.

**Comment by rfrenchseti** [comment]
Meeting today: Put a checkbox at the top of the cart column in the table view. Put an entry in the hamburger menu. Both should only be available on the browse tab.

**Comment by rfrenchseti** [comment]
Also change styling on hamburger menu to have much less vertical padding between items
