### ISSUE TITLE
gallery embedded data viewer behavior if you change the search

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#142]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

if you change the search and go back to gallery the data viewer will be open with nothing in it and no close button

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/141

**Comment by physicsguy42** [comment]
If you select an image in "browse results" to expand in side panel. Side panel image stays open even when changing to a search that doesn't include side panel image.
