### ISSUE TITLE
"Start Over" button should not clobber chosen columns

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#143]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

and probably other things

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/142

**Comment by rfrenchseti** [comment]
This is a part of a more general problem about separating the search criteria from the columns (including which ones are currently being sorted on).

**Comment by rfrenchseti** [comment]
It doesn't actually clobber the chosen columns.
