### ISSUE TITLE
Creation of side metadata box can cause referenced thumbnail to move off screen

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#145]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

on first opening a metadata box (first clicking a thumbnail) when it resizes the thumbnail column it can move the thumbnail that was clicked off screen. Make it so it resizes gallery column first and lands the thumbnail in the viewport then place the metadata box. 

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/144

**Comment by rfrenchseti** [comment]
This will no longer be an issue with the new modal dialog box.

**Comment by rfrenchseti** [comment]
There is no longer a side metadata box.
