### ISSUE TITLE
OPUS should send email when cart references non-existent files

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#153]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

see logs 10am to 11:20 EDT 5/14 cart issued 'not found' voyager images

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/153

**Comment by basilleaf** [comment]
_Original comment by_ **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**:

---

https://docs.djangoproject.com/en/1.8/topics/email/

**Comment by rfrenchseti** [comment]
This is handled through analysis of the error log files now.
