### ISSUE TITLE
OPUS needs a better custom 404 page

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#155]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

make a 404 page because the one it is using is snarky and with a broken image

so either make a new one or remove the current one so it uses default for server

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/155

**Comment by rfrenchseti** [comment]
I don't even see a way to trigger a 404 page these days.
