### ISSUE TITLE
API calls need to return startobs/limit/result_count metadata with each response

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#156]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

when a large result is returned there should be a field that describes the total result count, current limit, and page. This is common in json APIs around the web and now I see why it is so helpful.. 

Here is background on how this came up:

Begin forwarded message:
On May 22, 2015, at 12:01 PM, Michael Aye wrote:

Hi Lisa,

how are you?

I am noticing an upper limit of 100 results for the API requests?

This one for example delivers 2261 results on the website, but the API keeps telling me 100:

'http://pds-rings-tools.seti.org/opus/api/files.json?instrumentid=Cassini+ISS&target=S+RINGS&projectedradialresolution1=0.5&projectedradialresolution2=2'

Did you have a limit put in for testing?

Michael

From: Lisa Ballard lballard@seti.org
Date: May 22, 2015 at 12:30:40 PM PDT
To: Michael Aye <>

Hi Michael! 

You can control how many results are returned by setting the limit variable in the url, so for example here at the end of the url I’ve added ‘&limit=3000' to assure we get all results for this particular search:

http://pds-rings-tools.seti.org/opus/api/files.json?instrumentid=Cassini+ISS&target=S+RINGS&projectedradialresolution1=0.5&projectedradialresolution2=2&limit=3000

The API only returns 100 results at a time, ‘pages’ if you will. You can navigate the pages by setting the page variable in the url, like here I’ve added page=5 at the end.

http://pds-rings-tools.seti.org/opus/api/files.json?instrumentid=Cassini+ISS&target=S+RINGS&projectedradialresolution1=0.5&projectedradialresolution2=2&page=5

This behavior is actually by design, as some large results will spin for awhile to serve thousands of results.. but I think since you asked it could be made clearer what is happening in the response itself. For example there could be another variable besides ‘data’ that tells you things like what page you are on, what the current limit is set to, and what the total result count is.. so I’m going to add this to our issue tracker for a future improvement. 

hope this helps!  
-lisa

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/156

**Comment by rfrenchseti** [comment]
This is done for dataimages.json but needs to be ported to data.json and images.json
