### ISSUE TITLE
table view - add thumbnail as optional column

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#160]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

Rob French requested. 

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/160

**Comment by rfrenchseti** [comment]
I honestly don't even remember why I wanted this now.
