### ISSUE TITLE
Implement "Preprogrammed Ranges"

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#162]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

Useful Ranges were never ported to OPUS 2 but they appear in OPUS 1 ![Screen Shot 2015-06-12 at 6.33.16 PM.png](https://bitbucket.org/repo/ex8BEA/images/1098419844-Screen%20Shot%202015-06-12%20at%206.33.16%20PM.png)

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/162

**Comment by rfrenchseti** [comment]
Implementation ideas:

- The details of "useful ranges" should be maintained in Python and served to the JavaScript along with a numerical input widget. The useful ranges can be encoded as a list containing a series of descriptions and value ranges.
- The useful ranges will be available as a popup box or as a selectable dropdown menu. When a range is chosen, the numerical fields will be filled in.

**Comment by rfrenchseti** [comment]
Also, to support the example given in the original bug report, the JSON should allow the encoding of categories, with each category containing its own set of descriptions and value ranges.

**Comment by rfrenchseti** [comment]
As an added bonus, we could have the same thing work for string fields. It wouldn't be a "range", but a single value.

**Comment by rfrenchseti** [comment]
Another good thing for ranges would be wavelength - for example, have selections for each useful color along with its wavelength range.

**Comment by rfrenchseti** [comment]
- Whenever there's range info, we always show the dropdown with the categories, with the appropriate ranges hidden/shown based on what the user has typed so far. There might be zero ranges, one range, or multiple ranges available. When the user hasn't typed anything, all the ranges are shown.
- When there is one or more ranges shown, disable verification of the input and show a "valid input" border
- When there are zero ranges shown, go ahead and do verification normally. This will catch the case of the user typing in a range name that doesn't exist, as well as handling the normal case of just typing in numbers like they normally do.
- When the user hits enter, if there's a single range shown, pretend the user just clicked on it and fill in both min/max boxes. If there are zero or multiple ranges shown, then just validate it as normal and let the back end decide what to do with it.

**Comment by rfrenchseti** [comment]
For wavelength, we want:
- PDS4 wavelength ranges
- CRC color names
- Various photometric systems: https://en.wikipedia.org/wiki/Photometric_system

**Comment by rfrenchseti** [comment]
From Matt:

I wonder whether some ring features might be ill-suited to this type of treatment.  The Methone ring, for example, not only has very fuzzy boundaries but is very faint.  It is not going to be visible in the vast majority of images turned up by any search governed simply by an inner and outer boundary. 

---

From Mark:

True. Of course, the user can also constrain the search to high phase angles, which would make sense in the case of the Methone ring.

Beyond that, we have wanted to add the ability to constrain an image search based on sensitivity, e.g., minimum detectable I/F. I think Rob has figured out a rough mapping from ISS filter names and exposure time to I/F per DN, which is basically what we would need to implement that.

---

From Matt:

I think my suggestion is that maybe certain rings should not be in OPUS in this way.  My reasoning is that we shouldn’t advertise that we do something unless we are confident we can do it well, and I think current searches we can enable for these structures will mostly yield data that don’t show those structures. 
Just limiting to those that have been mentioned here, I’d suggest this for the Methone ring, Anthe ring, Pallene ring, and the Unnamed ring of Neptune (which is the Galatea co-orbital, no?). 

The same may be true of the Arago ring, which is a faint and fuzzy appendage that extends outward from the Le Verrier ring. 

Colwell et al. (2009, Saturn book) pointed out that the Dawes Ringlet is actually not a true ringlet, as it is not separated from the main disk on the inward side.  They called it an “embedded ringlet,” which is the same category as the plateaux in the C ring.  They do fix the outer boundary at 90200, which is what Danny answered.
