### ISSUE TITLE
Detail Page Loads too slowly, is not optimized for mobile

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#163]
image does not appear on top for mobile screens

initial page load can be slow..  
this might be related to this https://github.com/basilleaf/opus/issues/117 remove gallery from dom when viewing detail page might help and would also prolly fix [social sharing](https://github.com/basilleaf/opus/issues/117)

**Comment by rfrenchseti** [comment]
This doesn't seem to be an issue any more - at least the slow loading part. Mobile is a totally different problem we'll deal with separately.
