### ISSUE TITLE
Problem using thumbnail tools in Selections tab when selections do not appear in results tab

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#168]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

if the selections that appear on the selections tab are from a previous gallery run-through, that is if they aren't drawn on the results page, then you can't use the thumbnail tools in the Selections tab, because in method metadataboxHtml it fails to get opus.gallery_data[ring_obs_id][i] because that is in use by current gallery items

a possible fix would be to catch that exception and get results for that ring_obs_id from server at that moment. 

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/168

**Comment by rfrenchseti** [comment]
Waiting on a rewrite of the Selections code.
