### ISSUE TITLE
Make opus_id column removable/reorderable

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#173]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

right now in column chooser you can't reorder or remove the ring_obs_id column, but this is not nice for the user, effectively makes user pay for our implementation problem under the hood..

the backend real problem appears in edit_collection_range.views inside: edit_collection_range (see todo): 

```
ring_obs_id = row[0] 
```

easy enough to inspect user defined columns and get that index right (as long as ring_obs_id is actually listed in the columns) 

but if ring_obs_id is removed from user desired columns completely, then: 

must handle this deeper in the stack, see the: 

```
data = getData(request,"raw")
```

and how getData and getPage (results.views) will gladly hand over rows that do not contain an id column if ring_obs_id is not in chosen columns, making them difficult to work with anywhere else

so perhaps getData/getPage always need to hand over an id column regardless of what is asked for, and everything that uses this result set has to know whether it wants to ignore that column in its response to user.. 

Note: Preventing user from moving or reordering this column is implemented in choose_columns.html and in browse.js (getColumnChooser and columnsDragged) When the deeper problem is fixed can remove this hack

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/173

**Comment by rfrenchseti** [comment]
Also see: https://github.com/SETI/pds-opus/issues/218

**Comment by rfrenchseti** [comment]
This is fixed in new_ui
