### ISSUE TITLE
Cosmetic improvements to product types on Detail tab

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#178]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

on data tab the links to products are labeled as their product type (FMT, IMG) which is not very descriptive. 

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/178

**Comment by basilleaf** [comment]
_Original comment by_ **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**:

---

via rob "Couldn't you just give the filename instead of the extension? That would be enough to say which is which. You can easily tell the difference as you mouse over the two FMT links."

**Comment by rfrenchseti** [comment]
PDS Products:
RESEAU_TABLE: TAB  LBL  DAT
COMPRESSED_RAW_IMAGE: IMQ
TIEPOINT_TABLE: TAB  LBL  DAT
CLEANED_IMAGE: LBL  IMG
GEOMETRICALLY_CORRECTED_IMAGE: LBL  IMG
CALIBRATED_IMAGE: LBL  IMG
DECOMPRESSED_RAW_IMAGE: LBL  IMG
preview_image: jpg  jpg  jpg  jpg

**Comment by rfrenchseti** [comment]
This is not really an issue any more because the product types are much more descriptive. Also duplicate filenames are removed.

**Comment by rfrenchseti** [comment]
I'm reopening this because it can still be a problem. Consider CIRS:

Browse Diagram (thumbnail): jpg jpg

COCIRS Planetary System Geometry: TAB LBL FMT TAB LBL TAB LBL TAB LBL TAB LBL TAB LBL TAB LBL TAB LBL TAB LBL TAB LBL TAB LBL TAB LBL TAB LBL TAB LBL

**Comment by rfrenchseti** [comment]
The page now looks like this. We could probably do a better job of formatting the filenames, perhaps indented under the header or in a table or something.

    Browse Diagram (full-size): POI0402140126_FP4_full.jpg IMG0402140126_FP4_full.jpg RIN0402140126_FP4_full.jpg 

    Browse Diagram (medium): RIN0402140126_FP4_med.jpg POI0402140126_FP4_med.jpg IMG0402140126_FP4_med.jpg 

    Browse Diagram (small): POI0402140126_FP4_small.jpg RIN0402140126_FP4_small.jpg IMG0402140126_FP4_small.jpg 

    Browse Diagram (thumbnail): RIN0402140126_FP4_thumb.jpg IMG0402140126_FP4_thumb.jpg POI0402140126_FP4_thumb.jpg 

    COCIRS Footprint Geometry on Bodies: POI0402140126_FP4.TAB POI0402140126_FP4.LBL POIDATA.FMT 

    COCIRS Footprint Geometry on Rings: RIN0402140126_FP4.TAB RIN0402140126_FP4.LBL RINDATA.FMT 

    COCIRS Planetary System Geometry: GEO0402140126_617.TAB GEO0402140126_617.LBL GEODATA.FMT GEO0402140126_615.TAB GEO0402140126_615.LBL GEO0402140126_613.TAB GEO0402140126_613.LBL GEO0402140126_603.TAB GEO0402140126_603.LBL GEO0402140126_699.TAB GEO0402140126_699.LBL GEO0402140126_611.TAB GEO0402140126_611.LBL GEO0402140126_616.TAB GEO0402140126_616.LBL GEO0402140126_601.TAB GEO0402140126_601.LBL GEO0402140126_602.TAB GEO0402140126_602.LBL GEO0402140126_610.TAB GEO0402140126_610.LBL GEO0402140126_605.TAB GEO0402140126_605.LBL GEO0402140126_618.TAB GEO0402140126_618.LBL GEO0402140126_604.TAB GEO0402140126_604.LBL 

    COCIRS Target Body Identifications: TAR0402140126_FP4.TAB TAR0402140126_FP4.LBL TARDATA.FMT 

    Raw Data (calibrated unavailable): SPEC0402140126_FP4.DAT SPEC0402140126_FP4.LBL

**Comment by rfrenchseti** [comment]
Also perhaps we could make "PDS Products" an expandable header so you don't have to see all these filenames unless you care.

**Comment by rfrenchseti** [comment]
I'm leaving open for the cosmetic issue.

**Comment by rfrenchseti** [comment]
This is really not a problem.
