### ISSUE TITLE
Previewing movies

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#180]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

movies don't have a way to preview them

and they don't have a nice handling in their detail view

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/180

**Comment by rfrenchseti** [comment]
Movies are not supported at all right now.
