### ISSUE TITLE
No New Horizons Mission Constraints in database

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#197]

**Comment by rfrenchseti** [comment]
It's called Spacecraft Clock Count1, which might indicate a problem in param_info.

**Comment by rfrenchseti** [comment]
The entire obs_mission_new_horizons table in OPUS is empty. This is why there is no spacecraft_clock_count.

Also, the heading for New Horizons Mission Constrain(t)s is spelled wrong.

**Comment by rfrenchseti** [comment]
There also appear to be no models for TelemetryApplicationId and MissionPhase.

**Comment by rfrenchseti** [comment]
For right now "partables" has been updated to have "NHXXX" as the trigger_val so the NH General Constraints tab is never activated.

**Comment by rfrenchseti** [comment]
Fixed in the new import pipeline
