### ISSUE TITLE
New Horizons instruments have no green hinting numbers, no gray-out behaviors 

### ISSUE THREAD

**Issue by physicsguy42** [SETI/rms-opus#207]
If open the mission widget and select the Cassini mission, then open the Instrument Name widget
only the Cassini instruments should be black with non-zero numbers next to them and other instruments should be grey with a zero. However, both New Horizons LORRI and MVIC are black with no number (zero or otherwise) next to them.

![image](https://cloud.githubusercontent.com/assets/98707/20817369/17eefb7c-b7dc-11e6-8f23-04878a4a65b0.png)

Additionally, if I select New Horizons only in the instrument widget all the instruments are grey except LORRI and MVIC (as it should be) but there no numbers next to the New Horizons instruments.

![image](https://cloud.githubusercontent.com/assets/98707/20817373/214fa4c8-b7dc-11e6-990f-b91b32b194f6.png)

**Comment by basilleaf** [comment]
I wonder why your images aren't showing up here and instead its showing the link (i fixed)

![image](https://cloud.githubusercontent.com/assets/98707/20817354/ffc15b94-b7db-11e6-8afe-c38567ab8394.png)

**Comment by physicsguy42** [comment]
I donno, that's how it did it when I dropped the image in.
