### ISSUE TITLE
Needs to be more obvious that Surface Geo only applies to certain instruments

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#208]
I put this here, because people weren't noticing that surface geometry didn't apply to certain instruments (so you could accidentally hit zero a lot) but that particular pain point may have been removed with this commit

via @matthewtiscareno

A couple ideas:

It might be good to make this warning more explicit. It currently reads “Supported instruments: ”. Perhaps change this to “PLEASE NOTE: This metadata is only supported for ; choosing constraints on these parameters will exclude data from all other instruments.”
It might also be good for the warning to appear in the applet, and not just the sidebar.
Should we consider changing instrument names from, e.g., “COISS” ==> “Cassini ISS” so that they are more immediately understandable?

**Comment by rfrenchseti** [comment]
There have been various usability improvements to surface geo that should solve this now.
