### ISSUE TITLE
Can we make Intended Targets and Surface Geometry Targets one single widget?

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#211]
i think this would be less confusing. Is there a reason to have them separate? 

so then depending on which target they select a surface geo tab could be triggered in the menu.. 

still give access to both Intended Target Name and Surface Geometry Target Name in search results 

I may be missing something.. this is a proposal. 

this would close #13   and #208

**Comment by rfrenchseti** [comment]
Not going to support this.
