### ISSUE TITLE
New Horizons target list doesn't take into account targets obscuring each other

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#213]
right now the New Horizons metadata pipeline is not set to check whether targets are obscuring each other. (ie see [this observation](http://tools.pds-rings.seti.org/opus#/planet=Pluto&surfacegeometrytargetname=CHARON&view=detail&browse=gallery&colls_browse=gallery&page=1&gallery_data_viewer=true&limit=100&order=time1&cols=ringobsid,planet,target,phase1,phase2,time1,time2&widgets=surfacegeometrytargetname,planet,target,planet,surfacegeometrytargetname,planet,surfacegeometrytargetname&widgets2=&detail=P_IMG_NH_LORRI_0299174713) which is Pluto but has surface geo for both Pluto and Charon, Charon being completely obscured) 

Mark is going to re-run it all with that switch flipped

**Comment by rfrenchseti** [comment]
This still happens today.

**Comment by rfrenchseti** [comment]
Kamino closed and cloned this issue to [SETI/pds-webserver](https://github.com/SETI/pds-webserver/issues/16)
