### ISSUE TITLE
startobs is ignored when coming in from pasted URL

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#219]
it displays the correct page, but the page # indicator always says 1.

**Comment by rfrenchseti** [comment]
Actually this is worse than that now. It puts the page number back to page 1 and shows page 2 (for no obvious reason).

**Comment by rfrenchseti** [comment]
And now it ignores startobs entirely...It always puts the slider at obs 1. Note this also needs to be fixed for cart_startobs.

**Comment by rfrenchseti** [comment]
Hopefully this will also allow page reload (Ctrl+R) to stay at the same obs.
