### ISSUE TITLE
COISS composite filter searching is broken

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#224]
via bug report: 

I made a query on the Cassini ISS images with the `VIO` filter:

http://tools.pds-rings.seti.org/opus#/surfacegeometrytargetname=TITAN&timesec1=2004-183&timesec2=2004-185&instrumentid=Cassini+ISS&FILTER=VIO

I got 1 image (as expected), but I can also see in the `Filter` section that 14 images are also available with the `IRPOL+CB3` filters (which is a polarized filter on which I am interested currently). But, when I click on it, the request changes to:

http://tools.pds-rings.seti.org/opus#/surfacegeometrytargetname=TITAN&timesec1=2004-183&timesec2=2004-185&instrumentid=Cassini+ISS&FILTER=IRPOL+CB3

and I got nothing...

I noticed that the problem is the same on every filter combinations with a `+` sign in the query. Hopefully the fix should be very easy to implement, you just need to replace the `+` sign by its ASCII format `%2B`. And now, it works:

http://tools.pds-rings.seti.org/opus#/surfacegeometrytargetname=TITAN&timesec1=2004-183&timesec2=2004-185&instrumentid=Cassini+ISS&FILTER=IRPOL%2BCB3

**Comment by rfrenchseti** [comment]
Actually this doesn't work for me with the %2B either.

**Comment by rfrenchseti** [comment]
Now it works with %2B. There was another bug hiding this potential fix.
