### ISSUE TITLE
Need local fallback for CDN for Bootstrap and JQuery

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#26]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

jquery cdn links in header.html and footer.html need local fallback

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/24

**Comment by rfrenchseti** [comment]
See here:
https://www.hanselman.com/blog/CDNsFailButYourScriptsDontHaveToFallbackFromCDNToLocalJQuery.aspx

We need a fallback for Bootstrap, too. Here is example code:
https://forum.freecodecamp.org/t/using-a-fallback-code-in-case-bootstraps-cdn-is-down/160753/3
