### ISSUE TITLE
Details page has duplicate data sometimes

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#293]
Sometimes when you select an image and "Show Details", the Details tab has redundant information, like multiple copies of the ring geometry. If you refresh the page, the redundant info goes away. This might be some kind of race condition.

**Comment by michaelaye** [comment]
This URI, which should be the details for only one ISS image, gives me over 4000 lines, I estimated that's all meta-data, several dozen times over? It seems like all subsections of the meta-data are repeated:

https://tools.pds-rings.seti.org/opus#/target=S+RINGS&instrumentid=Cassini+ISS&projectedradialresolution1=&projectedradialresolution2=1&camera=Narrow+Angle&FILTER=CLEAR&DATACONVERSIONTYPE=12BIT&view=detail&browse=gallery&colls_browse=gallery&page=1&gallery_data_viewer=true&limit=100&order=time1&cols=ringobsid,planet,target,phase1,phase2,time1,time2&widgets=INSTCMPRSRATIO1,GAINMODEID,DATACONVERSIONTYPE,FILTER,camera,projectedradialresolution1,instrumentid,target&widgets2=&detail=S_IMG_CO_ISS_1711402000_N

**Comment by michaelaye** [comment]
Refreshing the page indeed removed all copies, but it hugely slows down the response time the first time it loads, because of this.

**Comment by rfrenchseti** [comment]
It doesn't seem to be specific to any kind of query. It's just a race condition in the Details tab when you display metadata for any result.

**Comment by rfrenchseti** [comment]
We can't reproduce this any more.

**Comment by michaelaye** [comment]
I just did here:

http://dev.pds-rings.seti.org:8000/opus/#/instrument=Cassini+ISS&COISScamera=Narrow+Angle&target=S+Rings&timesec1=2017-06-01&timesec2=&RINGGEOringradius1=74000&RINGGEOringradius2=92000&RINGGEOprojectedradialresolution1=&RINGGEOprojectedradialresolution2=1&view=detail&browse=gallery&colls_browse=gallery&page=1&gallery_data_viewer=true&limit=100&order=time1&cols=opusid,planet,target,time1,time2&widgets=RINGGEOprojectedradialresolution1,RINGGEOringradius1,timesec1,COISScamera,instrument,planet,target&widgets2=&detail=COISS_2113-1875228144_1875491141-N1875233884_1

**Comment by michaelaye** [comment]
The way to reproduce it is to go back and forth between the `browse` view, pick one, then you go to the `details` view, go back to `browse` again. I only needed 3 rounds to get doubled sections again.

**Comment by rfrenchseti** [comment]
I've gone back and forth dozens of times and I still can't get it to happen. Can you be more explicit with what you're doing? When you say "pick one" are you hitting the "(i)" icon on the thumbnail? Are you letting the details page load all the way before going back and selecting another? Are you examining the details page before going back to browse?

**Comment by michaelaye** [comment]
* Click on above link
* Browse results
* Click on Thumbnail
* View Details
* Normal list
* Browse results
* Click on different thumbnail
* View Details
* List now is double length

After each step I wait until all loading is finished.

Using Chrome 67.0.3396.99 on macOS 10.12.6

**Comment by rfrenchseti** [comment]
WTF? Yes that does it. I think the magic difference is clicking on the "View Detail" link rather than the (i) icon. How bizarre. Thanks for tracking that down.

**Comment by rfrenchseti** [comment]
Found and fixed! To be deployed with the major upgrade.
