### ISSUE TITLE
Don't allow selection of more than one surface geo target

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#303]
If you select the Surface Geometry tab and click on "target name" and then select more than one target, only the first target shows up as a new menu with surface geometry options.

**Comment by rfrenchseti** [comment]
We will never support more than one surface geometry target. Thus the selections should be radio buttons, not checkboxes.

**Comment by rfrenchseti** [comment]
Reopening this because it has a problem when you refresh your browser window. For all sub-menus other than the one with the valid selection, it gives the message "Select a valid choice. ["XXX"] is not one of the available choices."

Honestly I thought I had fixed this once before in the surface geometry target widget. I think the trick is to not set a choice when creating the form widget if the given search option isn't one of the available choices.

**Comment by juzen2003** [comment]
So the issue is related to how django form verifies the data when there is one exists. The issue is there at the production site too on Intended Target Name. By changing MultipleChoiceField or ChoiceField to CharField and directly passing in choices in widget would fix the issue.

**Comment by rfrenchseti** [comment]
Fixed
