### ISSUE TITLE
Need web page that describes the meaning of Cassini activity names

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#315]
Rob Chancia would like the ability to have a drop-down box display all activity names, along with their meaning if known, rather than just a text search field.

**Comment by markshowalter** [comment]
This approach won’t work. The number of activity names is utterly enormous.

The best we could probably do is have links to documentation. Right now each team is writing up a summary of their different activity names. We could probably integrate that into the existing help system if the help system supports links to static webpages for more information.

On Apr 23, 2018, at 9:25 AM, Robert French <notifications@github.com<mailto:notifications@github.com>> wrote:


Rob Chancia would like the ability to have a drop-down box display all activity names, along with their meaning if known, rather than just a text search field.

**Comment by rfrenchseti** [comment]
We have the ability to link to a single external web site from the new dictionary. So we could either link to an external document that has the descriptions, or we could create our own internal web page that has links to multiple documents.

This does bring up another idea, though. There's no reason we couldn't do the real-time search box auto-fill like Google does. Type in the first few letters and be presented with a drop-down box of choices.

**Comment by markshowalter** [comment]
This would be a useful capability.

Target name is a good example where people might want to start typing and even with asteroids and comets, the number of potential matches would be limited.

On Apr 23, 2018, at 10:17 AM, Robert French <notifications@github.com<mailto:notifications@github.com>> wrote:


We have the ability to link to a single external web site from the new dictionary. So we could either link to an external document that has the descriptions, or we could create our own internal web page that has links to multiple documents.

This does bring up another idea, though. There's no reason we couldn't do the real-time search box auto-fill like Google does. Type in the first few letters and be presented with a drop-down box of choices.

**Comment by markshowalter** [comment]
We could easily create a single page with all this info.

On Apr 23, 2018, at 10:17 AM, Robert French <notifications@github.com<mailto:notifications@github.com>> wrote:


We have the ability to link to a single external web site from the new dictionary. So we could either link to an external document that has the descriptions, or we could create our own internal web page that has links to multiple documents.

This does bring up another idea, though. There's no reason we couldn't do the real-time search box auto-fill like Google does. Type in the first few letters and be presented with a drop-down box of choices.

**Comment by rfrenchseti** [comment]
Auto-fill of search strings is now under #316. I am changing this bug to be the need for a page to list activity names.

**Comment by rfrenchseti** [comment]
For now, Mitch will look at putting any documentation on the main website.
BYBTW 3/11/2021
