### ISSUE TITLE
Galileo has no SPACECRAFT_STOP_COUNT

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#318]
Currently we set the STOP count equal to the START count, but it should be possible to derive the STOP count from the START count and the exposure duration.

**Comment by rfrenchseti** [comment]
This will be done as part of the effort to redo the GOSSI surface/ring geometry. The new clock count will be included in the supplemental index.
BYBTW 3/11/2021

**Comment by jnspitale** [comment]
Added SPACECRAFT_STOP_COUNT as well as SPACECRAFT_PRECISE_STOP_COUNT and SPACECRAFT_PRECISE_START_COUNT

**Comment by matthewtiscareno** [comment]
Shouldn't that be SPACECRAFT_CLOCK_STOP_COUNT?

**Comment by jnspitale** [comment]
Yes.  I thought I corrected that.

On Jan 29, 2024, at 11:26 AM, Matthew Tiscareno ***@***.***> wrote:

﻿

Shouldn't that be SPACECRAFT_CLOCK_STOP_COUNT?
