### ISSUE TITLE
Mini detail pane should move with scrolling

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#348]
Go to the browse tab. Scroll down a ways. Select an image and pop up the mini detail pane on the left side. Now continue scrolling. The pane stays where it was and doesn't remain visible. I think it should retain its place on the physical screen so it's always visible.

**Comment by rfrenchseti** [comment]
Another possibility is to get rid of the mini-detail pane entirely and provide the information when you mouse-over an image instead.

**Comment by dstopp** [comment]
Removed the mini-detail page and replaced it w/a modal, so this issue is no longer relevant.
