### ISSUE TITLE
Thumbnails are stretched to be 100x100 pixels

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#369]
Hubble preview images are often not exactly 100x100. When the <img> tag is used without any sizing in gallery.html, you end up with a patchwork of sizes in the gallery view so that the thumbnails don't line up properly. I fixed this (sort of) by forcing the <img> to be width=100px height=100px. However, this stretches the image instead of padding. We need a more friendly HTML solution that just pads the edge with black and keeps the original aspect ratio the same, but forces the height and width to be 100px.

**Comment by rfrenchseti** [comment]
See HSTI1_2003

**Comment by dstopp** [comment]
currently working; just needs to be vertically centered/horizontally centered in div

**Comment by rfrenchseti** [comment]
Fixed
