### ISSUE TITLE
Observation Duration UVIS

### ISSUE THREAD

**Issue by physicsguy42** [SETI/rms-opus#400]
For Cassini UVIS, if I also select observation duration the min/max/null values above the data entry boxes are all at zero. If I put 0.0 and 1.0 into the min and max boxes respectively I get about 200000 results. One of the products (OPUS ID: COUVIS_0001-D1999_010-HDAC1999_010_05_01) has

Exposure Duration: None
Intended Target Name: NONE
Observation Duration: 0.0
Observation Start Time (UTC): 1999-010T05:01:56.575
Observation Stop Time (UTC): 1999-010T05:02:00.575

Not sure what the difference is between  Exposure Duration and Observation Duration but given the start and stop time at least one of them should be non-zero. This may actually not be be bug in OPUS but a "bug" in the UVIS metadata.

**Comment by rfrenchseti** [comment]
Yikes! This problem affects a lot more than UVIS. It's a one-character typo.
