### ISSUE TITLE
Column chooser needs "restore default columns" button

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#44]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/43

**Comment by basilleaf** [comment]
_Original comment by_ **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**:

---

I'm pushing this to 1.2 because the "start over" button achieves the same effect

**Comment by rfrenchseti** [comment]
Done in new_ui
