### ISSUE TITLE
Gallery: Getting sent back to top

### ISSUE THREAD

**Issue by physicsguy42** [SETI/rms-opus#454]
In gallery view of a large number of images sometimes 
the user gets "bounced" back to the top of the gallery (page 1) 
when trying to scroll past the last resolved page (maybe > 4 pages)
of results. This may only happen in the Chrome browser.

**Comment by rfrenchseti** [comment]
Yea, this actually happens even with one page of images if you use the scrollbar to scroll down "past" the bottom to load in a new page. It even happens on the Detail tab. It would be nice to fix this one before we do the complete rewrite of table/gallery because it's so annoying.
