### ISSUE TITLE
Implement unit indicators/selectors for numerical input widgets

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#46]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/45

**Comment by rfrenchseti** [comment]
Implementation ideas:

- There should be classes of units (e.g. distance, time) and each class should have a set of units that are available (e.g. nm, angstrom, micron, mm, meter, km, AU). The list of units is maintained in Django and served to the JavaScript when a numerical widget is created.
- There should be a default unit for each numerical field, taken from param_info, also served to the JavaScript.
- When displaying a numerical field (or pair of fields), there should be a single dropdown box that has all the possible units in it, and it should be preset to the default unit.
- There should be a new slug type, like q-type, that says which unit to use to interpret the input field. The default unit is used if no slug is specified.
- All unit conversion should be handled by the Python, with no intelligence in the JavaScript.
- **Looking at the Apache logs, some users want to be able to type the unit name after the numerical value like "625 nm" and we should support that, automatically changing the unit selected in the dropbox menu.**

**Comment by rfrenchseti** [comment]
We also need to show the units when displaying metadata, like "observation duration (secs)" or perhaps "observation duration: 45.0 secs".

**Comment by rfrenchseti** [comment]
The initial implementation of this is just going to consist of:

1) Choosing which units we support in the database
2) Putting the proper units in the table_schemas JSON files for all RANGE entries in all obs_* tables
3) Creating a dictionary that converts between the internal database unit abbreviations and the "pretty" versions we want users to see (such as "s" -> "seconds")
3) Modifying api_get_widget() to put the unit type in the widget title
4) Modifying get_metadata() to put the unit type in the metadata name

Later we will allow the user to select the specific units they want to use.

**Comment by rfrenchseti** [comment]
In the table_schemas JSON files, the "data_source" field tells you where the data comes from, and thus where to look to figure out the proper units.
- If it says "FUNCTION", then the second line is the name of a Python function in one of the "populate_xxx" files (sometimes with an instrument or mission name substituted in where obvious, like "obs_pds_<INST>_primary_file_spec" maps to "populate_obs_pds_COISS_primary_file_spec" for COISS volumes). You should look at the function to see if you can figure out what units it's producing.
- If it says TAB:index or TAB:supp_index then it's getting the data directly from the main index.tab file or supplemental_index.tab file, respectively. Then you look at the labels for those files to see if you can figure out the units. The second line is the name of the field in the label file. There are samples of each label file under opus/import/util/master_labels.

**Comment by juzen2003** [comment]
# Modifications:
# obs_wavelength.json
  * wavelength1, wavelength2
    * units: micron
    * form_type: RANGE%.4f
  * wave_res1, wave_res2
    * units: micron/pixel
    * form_type: RANGE%.4f
  * wave_no1, wave_no2
    * units: cm-1
    * form_type: RANGE%.4f
  * wave_no1_res, wave_no2_res
    * units: cm-1/pixel
    * form_type: RANGE%.4f

# obs_type_image.json
  * duration
    * units: seconds
    * form_type: RANGE%.4f

# obs_general.json
  * observation_duration
    * units: seconds
    * form_type: RANGE%.4f
  * declination1, declination2
    * units: degrees
    * form_type: RANGE%.6f
  * right_asc1, right_asc2
    * units: degrees
    * form_type: LONG%.6f

# obs_instrument_coiss.json
  * missing_lines
    * units: no unit
    * form_type: RANGE%d
  * image_number
    * units: seconds
    * form_type: RANGE%d

# obs_instrument_couvis.json
  * band1, band2, band_bin
    * units: no unit
    * form_type: RANGE%d
  * line1, line2, line_bin
    * units: no unit
    * form_type: RANGE%d
  * samples
    * units: no unit
    * form_type: RANGE%d
  * for above fields, change pi_units: null to "" to avoid displaying None on widget title

# obs_instrument_covims.json
  * ir_exposure, vis_exposure
    * units: milliseconds
    * form_type: RANGE%.1f

# obs_instrument_vgiss.json
  * usable_lines
    * units: no unit
    * form_type: RANGE%d
  * usable_samples
    * units: no unit
    * form_type: RANGE%d

# obs_mission_hubble.json
  * hst_proposal_id
    * units: no unit
    * form_type: RANGE%d
  * for above fields, change pi_units: null to "" to avoid displaying None on widget title

# obs_ring_geometry.json
  * ring_radius1, ring_radius2
    * units: km
    * form_type: RANGE%.3f
  * resolution1, resolution2, projected_radial_resolution1, projected_radial_resolution2
    * units: km/pixel
    * form_type: RANGE%.5f
  * range_to_ring_intercept1, range_to_ring_intercept2
    * units: km
    * form_type: RANGE%.3f
  * ring_center_distance
    * units: km
    * form_type: RANGE%.3f
  * longitude_wrt_observer1
    * units: km
    * form_type: LONG%.3f
  * longitude_wrt_observer2
    * units: km
    * form_type: RANGE%.3f
  * ring_azimuth_wrt_observer1
    * units: degrees
    * form_type: LONG%.3f
  * ring_azimuth_wrt_observer2
    * units: degrees
    * form_type: RANGE%.3f
  * sub_solar_ring_long, sub_observer_ring_long
    * units: degrees
    * form_type: LONG%.3f
  * solar_ring_elev1, solar_ring_elev2, observer_ring_elevation1, observer_ring_elevation2
    * units: degrees
    * form_type: RANGE%.3f
  * phase1, phase2, incidence1, incidence2, emission1, emission2
    * units: degrees
    * form_type: RANGE%.3f
  * north_based_incidence1, north_based_incidence2, north_based_emission1, north_based_emission2
    * units: degrees
    * form_type: RANGE%.3f
  * ring_center_phase, ring_center_incidence, ring_center_emission
    * units: degrees
    * form_type: RANGE%.3f
  * ring_center_north_based_incidence, ring_center_north_based_emission, solar_ring_opening_angle, observer_ring_opening_angle
    * units: degrees
    * form_type: RANGE%.3f
  * edge_on_radius1, edge_on_radius2, edge_on_altitude1, edge_on_altitude2
    * units: km
    * form_type: RANGE%.3f
  * edge_on_radial_resolution1, edge_on_radial_resolution2
    * units: km/pixel
    * form_type: RANGE%.5f
  * range_to_edge_on_point1, range_to_edge_on_point2
    * units: km
    * form_type: RANGE%.3f
  * edge_on_j2000_longitude1, edge_on_j2000_longitude2
    * units: degrees
    * form_type: LONG%.3f
  * edge_on_solar_hour_angle1, edge_on_solar_hour_angle2
    * units: degrees
    * form_type: LONG%.3f
  * j2000_longitude1, j2000_longitude2, solar_hour_angle1, solar_hour_angle2
    * units: degrees
    * form_type: LONG%.3f

# obs_surface_geometry_target.json
  * planetocentric_latitude1, planetocentric_latitude2, planetographic_latitude1, planetographic_latitude2
    * units: degrees
    * form_type: RANGE%.3f
  * iau_west_longitude1, iau_west_longitude2, solar_hour_angle1, solar_hour_angle2
    * units: degrees
    * form_type: LONG%.3f
  * observer_longitude1, observer_longitude2
    * units: degrees
    * form_type: LONG%.3f
  * finest_resolution1, finest_resolution2, coarsest_resolution1, coarsest_resolution2
    * units: km/pixel
    * form_type: RANGE%.5f
  * range_to_body1, range_to_body2
    * units: km
    * form_type: RANGE%.3f
  * phase1, phase2, incidence1, incidence2, emission1, emission2
    * units: degrees
    * form_type: RANGE%.3f
  * sub_solar_planetocentric_latitude, sub_solar_planetographic_latitude
    * units: degrees
    * form_type: RANGE%.3f
  * sub_observer_planetocentric_latitude, sub_observer_planetographic_latitude
    * units: degrees
    * form_type: RANGE%.3f
  * sub_solar_iau_longitude, sub_observer_iau_longitude
    * units: degrees
    * form_type: LONG%.3f
  * center_resolution
    * units: km/pixel
    * form_type: RANGE%.5f
  * center_distance
    * units: km
    * form_type: RANGE%.3f
  * center_phase_angle
    * units: degrees
    * form_type: RANGE%.3f

# api_get_widget
  * Update ui/templates/widget.html to print out unit at widget header
  * Add get_units function in paraminfo/models.py to print out units

# get_metadata
  * Update get_medata function in results/views.py to format displaying values in detailed page (trailing 0s are removed as well)
  * Update results/templates/results/detail_metadata*.html to print units in detail pages

**Comment by rfrenchseti** [comment]
- COISS image number should have no unit. It sort of pretends to be seconds, but it's really spacecraft clock count.
- COVIMS exposures should be in seconds in the database. Check the populate files to make sure we convert them, and then you'll have to change the decimal format by +3.
- For obs_ring_geometry, I'm surprised ring_radius1/2 is so imprecise (1-m resolution). We need to make this higher resolution, because there are upcoming data products, like radial occultation profiles, that will have much more detail.  Let's make this .6f.
- For obs_ring_geometry, longitude_wrt_observer is in degrees. ring_azimuth_wrt_observer2 should have the same form type as ring_azimuth_wrt_observer1 (LONG).

**Comment by rfrenchseti** [comment]
The first version of this has been fixed (displaying the internal units to the user). The second part (allowing the selection of new units) is yet to be done.

**Comment by rfrenchseti** [comment]
Current to do list:
- DONE - Change normalizeurl to enforce only one unit per search widget
- DONE - Change format string (%.3f) in normalizeinputs to adjust for difference in unit scale
- DONE - Change api/meta/range/endpoints to take a units= parameter to return the green min/max hints with the given units
- DONE - Come up with lists of available units
- DONE - Include default unit in fields.json output and API guide

Here are the units we currently use:

cm^-1 (wave number)
cm^-1/pixel (wave number resolution)
microns (wavelength)
microns/pixel (wavelength resolution)

degrees (RA, dec, various ring/surface geo latitude, longitude, lighting angles)

km (ring radius, ring edge on altitude, ring distance, surface geo distance)
km/pixel (ring/surface geo resolution)

seconds (all types of image/exposure duration)

milliseconds (COVIMS IR/VIS pixel/line exposure - should we have made these seconds to begin with?)

For each default unit, we can have a set of other units that can be selected by the user.

I think the immediately obvious ones are:

microns => microns, nm, angstroms

degrees => degrees, radians

km => km, Saturn radii, Jupiter radii, Neptune radii, Uranus radii  (m? feet? miles?)

seconds => seconds, milliseconds, maybe microseconds
milliseconds => milliseconds, seconds

**Comment by rfrenchseti** [comment]
/meta/range/endpoints now takes a units parameter and adjusts the return format accordingly:
```
http://127.0.0.1:8000/api/meta/range/endpoints/observationduration.json?units=milliseconds`
{"min": "0.0", "max": "50000000.0", "nulls": 11, "units": "milliseconds"}

http://127.0.0.1:8000/api/meta/range/endpoints/observationduration.json?units=seconds
{"min": "0.0000", "max": "50000.0000", "nulls": 11, "units": "seconds"}

http://127.0.0.1:8000/api/meta/range/endpoints/observationduration.json?units=minutes
{"min": "0.000000", "max": "833.333333", "nulls": 11, "units": "minutes"}

http://127.0.0.1:8000/api/meta/range/endpoints/observationduration.json?units=hours
{"min": "0.00000000", "max": "13.88888889", "nulls": 11, "units": "hours"}

http://127.0.0.1:8000/api/meta/range/endpoints/observationduration.json?units=days
{"min": "0.000000000", "max": "0.578703704", "nulls": 11, "units": "days"}
```
