### ISSUE TITLE
Ring Geometry Constraints

### ISSUE THREAD

**Issue by physicsguy42** [SETI/rms-opus#463]
In Ring Geometry Constraints the Observed Ring Radius widget appears broken. 

If I select  Cassini ISS as Instrument Name and S Rings as Target and then go down to 
Ring Geometry Constraints and click on Observed Ring Radius no widget shows up. The other widgets in the section appear to be fine.

**Comment by rfrenchseti** [comment]
It works fine for me...

**Comment by physicsguy42** [comment]
It seems fine in Firefox but doesn't work in Chrome

**Comment by rfrenchseti** [comment]
I'm using Chrome.

I think you must have a corrupted cache or something. Try starting Chrome over.  Settings -> Advanced -> Clear browsing data -> Cached images and files

**Comment by physicsguy42** [comment]
Hmm...if I start it in a new browser window it's fine. But from this URL it doesn't work

https://tools.pds-rings.seti.org/opus/#/view=search&browse=gallery&colls_browse=gallery&page=1&gallery_data_viewer=true&limit=100&order=time1&cols=opusid,instrumentid,planet,target,time1,time2,observationduration&widgets=planet,target&widgets2=&detail=

Maybe the "start over" doesn't really clear everything.

**Comment by rfrenchseti** [comment]
It works fine for me from that link. I think you have a transient browser issue. All "start over" does is erase any search constraints you've entered. It doesn't change anything else.

**Comment by physicsguy42** [comment]
So you think it's a bug in Chrome? I'll clear the cache as you suggested and see if I can get it to happen again.

**Comment by rfrenchseti** [comment]
I don't know what happened, but I don't think it's a bug in OPUS. Feel free to try to make it happen again, but there's no reason the ring radius widget is any different from any other one. It's possible that OPUS got confused if you clicked on things too rapidly.

**Comment by physicsguy42** [comment]
I don't know what "too rapidly" means but I did think was odd that it was the only widget that wasn't showing up.
