### ISSUE TITLE
Need test of VIMS products returned for observations with multiple downlink numbers

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#482]
The COVIMS observations listed below have multiple downlink copies, indicated by the "_1" or "_3" in the filename. Note that this downlink number is ignored when creating the new OPUS ID, so there is just a single OPUS ID for each pair. When you do a query on an OPUS ID, and then look at the Details page, download data using the Selections, or query using the "files" api, you should see all downlink versions presented, with the most recent version (highest number) first. I've attached two screenshots (old OPUS and new OPUS) showing the difference. We need tests that make sure this continues to work.

These observations are all in COVIMS_0006. You can find them by searching on the main name (v1490874598) as the primary file spec. Note that many of these also have a _002 version available. This version does NOT have multiple downlink copies. Thus you can test both cases, _001 and _002, and check that the number of downlinks returned is different.

v1490874598_1_001
v1490874598_3_001

v1490874654_1_001
v1490874654_3_001

v1490874707_1_001
v1490874707_3_001

v1490874775_1_001
v1490874775_3_001

v1490874823_1_001
v1490874823_3_001

v1490874878_1_001
v1490874878_3_001

v1490874946_1_001
v1490874946_3_001

v1490874999_1_001
v1490874999_3_001

v1490875052_1_001
v1490875052_3_001

![v1490874598_001-old](https://user-images.githubusercontent.com/6488118/48230319-6de62e00-e35f-11e8-8911-3f85f01cd230.png)
![v1490874598_001-new](https://user-images.githubusercontent.com/6488118/48230323-6faff180-e35f-11e8-9c6e-f484f24667a6.png)

**Comment by juzen2003** [comment]
Test has been run against the dev server to check if all above primary_filespecs have multiple downlinks in detailed page. Attached file is the log. The logic is to compare the number of images in json between 001 and 002 and make sure the number of 001 images are always larger than the count in 002. Image numbers in the following fields are checked: browse-thumb, browse-small, browse-medium, browse-full, covims-raw, covims-thumb, covims-medium, covims-full.

[20181114_dev_vims_downlinks_testing_log.log](https://github.com/SETI/pds-opus/files/2583344/20181114_dev_vims_downlinks_testing_log.log)

**Comment by rfrenchseti** [comment]
Looks good. If you aren't already doing it, please make sure the number of returns is >0 in all cases as well (both 001 and 002 versions).

I'll leave this bug open until the API testing has been merged into the deployment flow.

**Comment by juzen2003** [comment]
Image counts check for both 001 and 002 are added. If any of image fields has 0 image, it would print out error message.
