### ISSUE TITLE
J RINGS and S RINGS are confusing

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#486]
From "Tapella, Robert K (398H)" <Robert.K.Tapella@jpl.nasa.gov>

"When you choose Saturn Rings as a target, it is shown as “S Rings” which looks similar to “A Ring” but which isn’t a real thing; it takes time for scientists to realize that it’s a truncated label instead of a specific target"

I suggest we change the names to "Saturn Rings" and "Jupiter Rings" to avoid confusion.

**Comment by mit3ch** [comment]
I agree.

Mitch

**Comment by rfrenchseti** [comment]
I also changed U Rings and N Rings and J Minor Sat.

**Comment by rfrenchseti** [comment]
These have been renamed to "Saturn Rings", etc.
