### ISSUE TITLE
NICMOS metadata files have inconsistent names for apertures

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#491]
Some HSTNICMOS volumes have two different names for the same aperture:

"NIC1FIX" vs. "NIC1-FIX" (e.g. HSTN0_7429)
"NIC2FIX" vs. "NIC2-FIX" (e.g. HSTN0_7319)
"NIC3FIX" vs. "NIC3-FIX" (e.g. HSTN0_7181)

This confuses the import pipeline.

**Comment by rfrenchseti** [comment]
I believe the version with the dash is the correct one:

http://www.stsci.edu/itt/APT_help/P2PI_ENG21/ch13_nicmos8.html#1207057

**Comment by physicsguy42** [comment]
I sure that the values came straight from the associated fits header. However, I'll take a look at it. I can fix it for future releases with a few if statements to standardize the value for APERTURE_TYPE.

**Comment by rfrenchseti** [comment]
For now I've fixed it in the import pipeline, converting the non-dash versions to the dash versions.

**Comment by rfrenchseti** [comment]
Kamino closed and cloned this issue to [SETI/pds-webserver](https://github.com/SETI/pds-webserver/issues/9)
