### ISSUE TITLE
HSTI1_5262 has bad wavelength information for all observations

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#492]
All 120 images in HSTI1_5262 have the wrong values for wavelength min and max in the original LBL files.

From https://pds-rings.seti.org/holdings/volumes/HSTIx_xxxx/HSTI1_5262/DATA/VISIT_01/IDG201NLQ.LBL:

FILTER_NAME                     = "F845M"
CENTER_FILTER_WAVELENGTH        = 0.0844 <micron>
BANDWIDTH                       = 0.0079 <micron>
MAXIMUM_WAVELENGTH              = 0.0883 <micron>
MINIMUM_WAVELENGTH              = 0.0804 <micron>

These are off by a factor of 10. For example, maximum_wavelength should be 0.883 microns.

By comparison, look at https://pds-rings.seti.org/holdings/volumes/HSTIx_xxxx/HSTI1_3937/DATA/VISIT_05/ICPF05SFQ.LBL:

FILTER_NAME                     = "F845M"
CENTER_FILTER_WAVELENGTH        = 0.8436 <micron>
BANDWIDTH                       = 0.0787 <micron>
MAXIMUM_WAVELENGTH              = 0.8830 <micron>
MINIMUM_WAVELENGTH              = 0.8043 <micron>

**Comment by physicsguy42** [comment]
Probably a unit conversion error. I'll add it to my list of HST pipeline fixes.

**Comment by rfrenchseti** [comment]
Note it's only this one volume. Other WFC3 volumes using the same filters are correct.

**Comment by physicsguy42** [comment]
That is strange I just looked up the prop ID on MAST and the central wavelength is 8439 Angstroms (sometimes hubble updates filter characteristics). It's probably a good idea to double check my code even if the error only shows up for one propID.

**Comment by rfrenchseti** [comment]
We might want to special-case fix this inside of OPUS just so we have valid data available.

**Comment by rfrenchseti** [comment]
Kamino closed and cloned this issue to [SETI/pds-webserver](https://github.com/SETI/pds-webserver/issues/8)
