### ISSUE TITLE
Floating point metadata needs to be rounded off

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#498]
Right now we can have things like an observation duration of 0.1999999999999999. This should be rounded off to a reasonable number of digits.

**Comment by rfrenchseti** [comment]
In some cases, this information is in the label file. For example:

>     FORMAT                      = "F8.3"

In other cases, you'll have to figure out what's reasonable. For example a distance in km probably doesn't need accuracy to more than six digits to the right of the decimal (mm).

We need to:
- Add a new field to each obs_XXX.json file in table_schemas called "pi_format". This should be adjacent to "pi_units" since they go together.
- Populate each field with a Python-standard format like ".3f". Note that we don't need the number to the left of the decimal, since we don't have fixed-width fields.
- Change the definition of the param_info table to include this new field.
- Change the import pipeline to populate this field in param_info from the JSON file.
- Change the Django code to use this format when returning floating point data to the API, both in the return of metadata and in places like range_endpoints.

**Comment by juzen2003** [comment]
**Please refer to #46, modifications are made in json.**
  * units are rounded off based on .lbl, please check comment in json for reference .lbl files.
  * to display values in correct formats, the following files are updated for search/detailed pages:
    * update ui/templates/widget.html to print out unit at widget header
    * add get_units function in paraminfo/models.py to print out units
    * update get_medata function in results/views.py to format displaying values in detailed page 
    * update results/templates/results/detail_metadata*.html to print units in detail pages

**Comment by rfrenchseti** [comment]
Fixed.

**Comment by rfrenchseti** [comment]
Reopening because we have to deal with the mini-detail pane.

**Comment by rfrenchseti** [comment]
Fixed in all places now.
