### ISSUE TITLE
Mouse click behavior on thumbnails

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#502]
Change the way selections are done from the current "check mark" method to a more standard method that has the user clicking on a thumbnail to add it to the collection, control+click to add another one, and shift+click to add a range. To pull up the metadata, click on the "expand" icon. To pull up the details page, click on the (i).

**Comment by dstopp** [comment]
-clicking on image selects <no longer will pull up modal>; shift click etc will finish the range select and the 'checkmark' we currently are using will go away.
-add some help text describing new behaviour in nav

**Comment by rfrenchseti** [comment]
Recommended behavior:
- Click toggles the selection of the current thumbnail
- Shift+Click selects all images from the previous click if the previous click is selected; deselects all images from the previous click if the previous click is deselected

**Comment by rfrenchseti** [comment]
New new behavior:

- Left click on thumbnail: mini-dialog box slideshow
- Left click on (i): Details page
- Left click on shopping cart: Add or remove from selections
- Shift + Left click on shopping cart: Add or remove range from selections
- Left click on "hamburger": Context menu containing:
  - "Add to Cart" or "Remove from Cart" as appropriate
  - "Start Selection Range" or "End Selection Range" as appropriate
  - "Show Detail"
  - "Download All Products for Observation"
  - "Download CSV for Observation"
  - "Help"
