### ISSUE TITLE
Merge /opus/api_tests into test_api

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#514]
The current /opus/api_tests directory contains a test where various queries (found in a CSV file) are run against a live server and the number of results checked for sanity. This set of tests should be moved into /opus/applications/test_api and updated to have current slug names and result counts. This test should ONLY be run against live servers, not the local server, although it would be nice to have some kind of override that allows it to be run locally when specifically asked.

**Comment by juzen2003** [comment]
# Modifications: 
# Slug mappings (new_slug : old_slug)
  * {
    "insthost": "insthostid",
    "instrument": "instrumentid",
    "CASSINIobsname": "obsname",
    "RINGGEOphase1": "phase1",
    "RINGGEOphase2": "phase2",
    "RINGGEOemission1": "emission1",
    "RINGGEOemission2": "emission2",
    "RINGGEOprojectedradialresolution1": "projectedradialresolution1",
    "RINGGEOprojectedradialresolution2": "projectedradialresolution2",
    "RINGGEOnorthbasedemission1": "northbasedRINGGEOemission1",
    "RINGGEOnorthbasedemission2": "northbasedRINGGEOemission2",
    "surfacegeometrytargetname": "surfacetarget",
    "SURFACEGEOsaturnsubobserverplanetographiclatitude1": "SATURNsubobserverplanetographiclatitude1",
    "SURFACEGEOsaturnsubobserverplanetographiclatitude2": "SATURNsubobserverplanetographiclatitude2",
    "SURFACEGEOsaturncenterresolution1": "SATURNcenterresolution1",
    "SURFACEGEOsaturncenterresolution2": "SATURNcenterresolution2",
    "COISScamera": "camera",
    "mission": "missionid",
    "RINGGEOringradius1": "ringradius1",
    "RINGGEOringradius2": "ringradius2",
    "RINGGEOsolarringelev1": "solarringelev1",
    "RINGGEOsolarringelev2": "solarringelev2",
    "RINGGEOobserverringelevation1": "observerringelevation1",
    "RINGGEOobserverringelevation2": "observerringelevation2",
    "SURFACEGEOganymedeincidence1": "surfacegeometryGANYMEDEincidence1",
    "SURFACEGEOganymedeincidence2": "surfacegeometryGANYMEDEincidence2",
    "SURFACEGEOganymedeemission1": "surfacegeometryGANYMEDERINGGEOemission1",
    "SURFACEGEOganymedeemission2": "surfacegeometryGANYMEDERINGGEOemission2",
    "SURFACEGEOganymedesolarhourangle1": "surfacegeometryGANYMEDEsolarhourangle1",
    "SURFACEGEOganymedesolarhourangle2": "surfacegeometryGANYMEDEsolarhourangle2",
  }
# Slug value mappings: (new_value: old_value)
  * {
    "Saturn+Rings": "S+RINGS",
    "Jupiter+Rings": "J+RINGS",
  }
# Changes of expected values
  * 16 result counts (change from 17 to 16) "http://tools.pds-rings.seti.org/opus#/planet=Jupiter&target=ADRASTEA&mission=Galileo&view=search&browse=gallery&colls_browse=gallery&page=1&gallery_data_viewer=true&limit=100&order=time1&cols=ringobsid,planet,target,RINGGEOphase1,RINGGEOphase2,time1,time2&widgets=mission,planet,target&widgets2=&detail="
  * 26 result counts (change from 38 to 26) "http://tools.pds-rings.seti.org/opus#/planet=Jupiter&target=CALLISTO&mission=Cassini&quantity=Reflectivity&view=search&browse=gallery&colls_browse=gallery&page=1&gallery_data_viewer=true&limit=100&order=time1&cols=ringobsid,planet,target,RINGGEOphase1,RINGGEOphase2,time1,time2&widgets=quantity,mission,planet,target&widgets2=&detail="

# Changes these values to 0:
* 0 result counts (change from 28 to 0)
  "http://tools.pds-rings.seti.org/opus#/planet=Earth&insthost=Cassini&timesec1=1999-230T02:10:00.000&timesec2=1999-230T02:20:00.000&view=search&browse=gallery&colls_browse=gallery&page=1&gallery_data_viewer=true&limit=100&order=time1&cols=ringobsid,planet,target,RINGGEOphase1,RINGGEOphase2,time1,time2&widgets=&widgets2=&detail=M_IMG_HST_ACS_2003-05-09_J8FV05KYQ"
* 0 result counts (change from 123 to 0)
  "http://tools.pds-rings.seti.org/opus#/planet=Venus&mission=Cassini&instrument=Cassini+VIMS&wavelength1=0.4&wavelength2=0.8&view=search&browse=gallery&colls_browse=gallery&page=1&gallery_data_viewer=true&limit=100&order=time1&cols=ringobsid,planet,target,RINGGEOphase1,RINGGEOphase2,time1,time2&widgets=wavenores1,specsize,polarizationtype,waveno1&widgets2=&detail=M_IMG_HST_ACS_2003-05-09_J8FV05KYQ"
* 0 result counts (change from 2 to 0)
  "http://tools.pds-rings.seti.org/opus#/planet=Venus&mission=Cassini&instrument=Cassini+ISS&wavelength1=0.70&wavelength2=0.75&view=search&browse=gallery&colls_browse=gallery&page=1&gallery_data_viewer=true&limit=100&order=time1&cols=ringobsid,planet,target,RINGGEOphase1,RINGGEOphase2,time1,time2&widgets=wavelength1&widgets2=&detail=M_IMG_HST_ACS_2003-05-09_J8FV05KYQ"

**Comment by rfrenchseti** [comment]
The reason for the difference in "26 result counts (change from 38 to 26)" is that we now mark the measurement quantity as "EMISSION" if the Cassini ISS filter is in the UV. All of the images that are missing in the current system have UV filters.

I don't know why "16 result counts (change from 17 to 16)" happens. There are clearly only 16 images of Adrastea, and the final image given by the old system is obviously of Callisto. I think the old data was bad.

The other three changes (Earth and Venus) are expected with our new definition of Planet.
