### ISSUE TITLE
Missing ISS file in index

### ISSUE THREAD

**Issue by michaelaye** [SETI/rms-opus#522]
I just found that both the ISS full index `COISS_2999_index.tab` and the ring summary index `COISS_2999_ring_summary.tab` are missing this ISS file that is available via OPUS:

n1878596676

https://tools.pds-rings.seti.org/opus/#/target=Saturn+Rings&instrument=Cassini+ISS&RINGGEOringradius1=89000&RINGGEOringradius2=90000&COISScamera=Narrow+Angle&COISSfilter=CLEAR&RINGGEOprojectedradialresolution1=&RINGGEOprojectedradialresolution2=1&timesec1=2017-01-01&timesec2=&view=detail&browse=gallery&colls_browse=gallery&page=1&gallery_data_viewer=true&limit=100&order=time1&cols=opusid,instrumentid,planet,target,time1,observationduration,RINGGEOringradius1,RINGGEOringradius2&widgets=timesec1,RINGGEOprojectedradialresolution1,COISSfilter,COISScamera,RINGGEOringradius1,instrument,planet,target&widgets2=&detail=co-iss-n1878596676

```bash
$ cat COISS_2999_index.tab |grep 1878596676                                                          (py37)
klay6683@MacL3883|~/D/d/c/db
$ cat COISS_2999_ring_summary.tab | grep 1878596676                                                  (py37)
klay6683@MacL3883|~/D/d/c/db
$
```

while this index was downloaded a few days ago, with your timestamp of `2018-08-18`.

**Comment by michaelaye** [comment]
I also verified that the index has higher numbers than the missing one. Highest image number in the index is 1884114531, so above file should be in.

**Comment by michaelaye** [comment]
Same with `n1878596819`

**Comment by michaelaye** [comment]
And n1880813932

**Comment by michaelaye** [comment]
and n1880813812

**Comment by rfrenchseti** [comment]
I've forwarded to Mark

**Comment by michaelaye** [comment]
It looks simply like COISS_2115 was simply not indexed into the cumulative index?

<img width="566" alt="screenshot 2018-12-21 12 25 29" src="https://user-images.githubusercontent.com/69774/50359904-972bd980-051b-11e9-9b91-fa8eff6a839c.png">

**Comment by rfrenchseti** [comment]
Kamino cloned this issue to [SETI/pds-webserver](https://github.com/SETI/pds-webserver/issues/5)

**Comment by rfrenchseti** [comment]
This will be tracked internally not part of pds-opus
