### ISSUE TITLE
Thumbnails load too slowly

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#56]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

likely because they are being resized in the HTML

figure out: what size is the thumbnail going to be? is it reasonable to size it down in the html (good for retina?) and if so by how much is ok? or is it decide on a size and then make a set that size?

Or.. can this be remedied by CDN which it probably needs anyway? 

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/55

**Comment by rfrenchseti** [comment]
This is fixed because we now show thumbnails in their native size.
