### ISSUE TITLE
We need to add the HST datasets to the alert box identifying the support datasets.

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#68]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

version 1.1

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/67

**Comment by basilleaf** [comment]
_Original comment by_ **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**:

---

btw: I have no idea what this means

**Comment by physicsguy42** [comment]
I don't know what this means either :-o
