### ISSUE TITLE
Add add-to-collection in gallery preview side pane

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#69]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

and use icons for add-to-collection and view-details so it's more like the thumbnails

v 1.1

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/68

**Comment by rfrenchseti** [comment]
This will be the same as adding "add to collection" in the slideshow with the new UI design.

**Comment by rfrenchseti** [comment]
The metadata dialog now has the same features as the gallery thumbnails.
