### ISSUE TITLE
can't tell what mults are selected, instead of checkbox make them more like buttons

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#71]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

version 1.1

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/70

**Comment by rfrenchseti** [comment]
I don't see any problem with mult selection checkboxes.
