### ISSUE TITLE
Safely escape input fields before inserting into URL

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#719]
A061: The user can enter a raw URL string like "&observationduration1=10" into any range or string field and it gets pasted into the URL verbatim, allowing people to really mess with the URL. These kinds of strings need to be escaped for safety.

**Comment by juzen2003** [comment]
NOTE: In pull request https://github.com/SETI/pds-opus/pull/812, we encode characters like "&" in hash before updating URL or calling API. So whenever the string field, numerical field, or check boxes contain special characters, most characters will be properly encoded before passing into API calls as a search value and Django will handle the decoding at the backend automatically.  "," is the only exception and causes issues. When "," exists in a string or numerical field value, either it's passed into API calls as "%2C" or comma, Django will decode it as ",". And we can't tell if "," is part of the actual value for a slug key or is used to separate multiple values for a slug key. We will have search Django document and see if there is a proper way to control the decoding in Django when revisiting this issue later.

**Comment by rfrenchseti** [comment]
I am deferring this for now because it doesn't matter until we eventually permit the use of multiple values for numeric or string inputs.

**Comment by rfrenchseti** [comment]
This is no longer relevant because we implemented multiple search terms using separate clauses.
