### ISSUE TITLE
Allow browser search to work properly with perfect scrollbar on detail page

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#733]
Request from Matt Tiscareno:

A105: When you use Ctrl+F in the browser to search for a text string and the found location is off the bottom of the screen, the scrollbar does not move to make it visible. It worked in the old OPUS.

**Comment by juzen2003** [comment]
Ctrl + F search scroll will not work properly with perfect scrollbar. Please see the followings:
https://github.com/mdbootstrap/perfect-scrollbar/issues/467
https://github.com/mdbootstrap/perfect-scrollbar/wiki/Caveats

If we add the workaround mentioned in the the issue page:
```/* detail tab */
.op-detail-metadata {
    /* setting container overflow to scroll and hide webkit scrollbar is
    the workaround for ctrl + F search scroll to work with perfect scrollbar */
    overflow-y: scroll !important;
}

/* As mentioned above, this is part of steps to make ctrl + F search scroll
to work with perfect scrollbar */
.op-detail-metadata::-webkit-scrollbar {
    display: none;
}
```

Ctrl + F search scroll will work fully in Chrome, but partially in FF and Opera.
In FF, we will see the overlapped scrollbar (default one and ps) even if we set display none for webkit scrollbar. (-webkit-scrollbar is not supported for FF: https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar)
In Opera, scrolling won't work if we want to drag and scroll.

The change is updated in my repo for experiment: https://github.com/juzen2003/pds-opus/ 
Branch: search_in_detail_page_issue_733

**Comment by rfrenchseti** [comment]
The final fix doesn't work for Opera or FF under Linux but seems to work for all others.

**Comment by ArturGudiev** [comment]
> Ctrl + F search scroll will not work properly with perfect scrollbar. Please see the followings:
> [mdbootstrap/perfect-scrollbar#467](https://github.com/mdbootstrap/perfect-scrollbar/issues/467)
> https://github.com/mdbootstrap/perfect-scrollbar/wiki/Caveats
> 
> If we add the workaround mentioned in the the issue page:
> 
> ```
> .op-detail-metadata {
>     /* setting container overflow to scroll and hide webkit scrollbar is
>     the workaround for ctrl + F search scroll to work with perfect scrollbar */
>     overflow-y: scroll !important;
> }
> 
> /* As mentioned above, this is part of steps to make ctrl + F search scroll
> to work with perfect scrollbar */
> .op-detail-metadata::-webkit-scrollbar {
>     display: none;
> }
> ```
> 
> Ctrl + F search scroll will work fully in Chrome, but partially in FF and Opera.
> In FF, we will see the overlapped scrollbar (default one and ps) even if we set display none for webkit scrollbar. (-webkit-scrollbar is not supported for FF: https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar)
> In Opera, scrolling won't work if we want to drag and scroll.
> 
> The change is updated in my repo for experiment: https://github.com/juzen2003/pds-opus/
> Branch: search_in_detail_page_issue_733

@juzen2003  If my code is 
```
<perfect-scrollbar> 
...
</perfect-scrollbar>
```
what is container? The upper tag itself?

**Comment by juzen2003** [comment]
It's the tag that the ps is attached to. (It will have "ps" as its class)
