### ISSUE TITLE
Removing items from cart page screws up caching

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#739]
If you remove an item from the cart on the Cart tab and then scroll down enough that a new page gets fetched, the starting obs# retrieved will be incorrect because the backend knows the removed item is gone, but the JS is still holding a place in the DOM for it. This means there will be missing thumbnails.

**Comment by rfrenchseti** [comment]
Suggested solution: Have a "recycle bin" for removed selections. When a selection is removed on the cart page, take it out of the DOM instantly but put it in the recycle bin. The recycle bin would probably be a new tab.

When an item is removed from the cart, the product info will have to be updated because the specific product types might change. This will wreck havoc with checkboxes unless we're careful to preserve what the user previously selected.

**Comment by rfrenchseti** [comment]
Also, we will need to implement the recycle bin in the back end. This could be done in multiple ways, but the easiest might be to add a field to the existing "cart" table that says whether the items is in the recycle bin or not. The various JOINs would have to be modified to select the proper value for that flag. This has the advantage of making things like dataimage.json and the __cart operations easy to modify, simply by including a &recyclebin=0/1 flag in the URL.

**Comment by dstopp** [comment]
-the tooltip icons at the bottom of the image on the cart will need to be modified such that delete an image goes to the recycle pile, vs just setting a class on the image <today>.
-when an observation is deleted from the cart, that observation should be deleted from the cart DOM in both browse and table views to avoid the need to retrieve the cart data and flash the user.  In addition, the observations in the cart page will need to be renumbered in the DOM bits where the observation number is kept.

**Comment by rfrenchseti** [comment]
This will be fixed by this pull: https://github.com/SETI/pds-opus/pull/835
The recycle bin idea is moved to a separate issue
