### ISSUE TITLE
when clicking add-range the whole thumbnail should behave as the checkmark

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#79]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

v 1.1

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/78

**Comment by physicsguy42** [comment]
It looks like to add a range of images, I need to click on the actual "check mark" in the first and last image in the series. It looks like the requirement here is to be able to just click anywhere in the image to choose the start or end image.
