### ISSUE TITLE
Very short browser can cause infinite scrolling to repeat endlessly

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#795]
When the browser is very short, it's possible for the browse scrollbar to stay below the infinite scroll trigger threshold, causing it to scroll and scroll and scroll...
Possible fixes are reducing the size of the threshold or the size of the scrollbar. It would be best to make these depend on the height of the browser window.

**Comment by juzen2003** [comment]
This issue is seen on iphone Safari, but not on iphone Chrome, Firefox, and Opera. I will check again when I have access to another iphone on Weekend.

**Comment by rfrenchseti** [comment]
Can't reproduce on any iPhone
