### ISSUE TITLE
Allow removal of search constraints by clicking on search field name

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#843]
Request from Mark:

In Select Metadata, when you click on a field name, it adds it to the list, and when you click on it again, it removes it. We should do the same thing on the main search page. Right now when you click on a field name it adds the widget. When you click on a field that is already selected, it should remove the widget. **However**, if the widget has some kind of constraint already entered, it should pop up a modal dialog saying "You are trying to remove a search field that has constraints. Would you like to remove the constraints and the search field or keep the search field as it is?" And have buttons "Remove" and "Keep".

**Comment by dstopp** [comment]
Minor bug in the production version  - Select a surface geometry target. Select some target-specific field. Close the surface geometry target widget with the "X". Answer YES to the confirmation. The widgets go away, but the menu doesn't get updated. The target constraints should be removed.
