### ISSUE TITLE
column chooser / table view - shouldn't blink out when adding/removing columns loads

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#85]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

v 1.2

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/84

**Comment by rfrenchseti** [comment]
This seems to be fine.
