### ISSUE TITLE
column chooser group selection not there

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#87]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

group header checkbox 

v 1.2

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/86

**Comment by rfrenchseti** [comment]
I have no idea what this means, but the column chooser appears to be OK as-is.
