### ISSUE TITLE
When the cart is empty, you can still see a slider with a large number in it

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#908]
Right now when the cart is empty, all the cart nav fields are greyed out, but not invisible. This means you can still see the slider in the state it used to be in. See attached screenshot for an example. I think it would be better to hide the nav items completely instead of just greying them out. Or disable them so the "empty cart" message is at the top.

To reproduce this, but a lot of things in the cart, move the slider to the middle, then empty the cart.

![11-24-2019 11-08-40 AM](https://user-images.githubusercontent.com/6488118/69499805-dfc9e080-0eaa-11ea-9d59-e501886d8001.png)

**Comment by rfrenchseti** [comment]
It should actually set the slider value to 1 when the cart is empty, too, even if the user can't see it. Otherwise when the user goes to add items to the cart later and returns to the cart tab, the slider will be where they left it even though the cart contents have completely changed.

**Comment by dstopp** [comment]
note: same thing happens if you set your search parameters to result in an empty list - the browse slider remains in the middle w/a spinner or previous number.
