### ISSUE TITLE
deployment could be smarter in how it's using memcache

### ISSUE THREAD

**Issue by basilleaf** [SETI/rms-opus#91]
Originally reported by: **lisa ballard (Bitbucket: [basilleaf](https://bitbucket.org/basilleaf), GitHub: [basilleaf](https://github.com/basilleaf))**

---

right now memcache is rebooted on every deploy and after almost every change

would be cool to have some python script micromanagement over keys so you don't have to flush entire system to refresh a few keys.. 

maybe something like https://github.com/pinterest/pymemcache

---
- Bitbucket: https://bitbucket.org/ringsnode/opus2/issue/90

**Comment by rfrenchseti** [comment]
This is an opus-admin issue.
