### ISSUE TITLE
Thumbnails in table view disappear when browser is narrow

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#960]
The mini-thumbnails in the table view are not a fixed width. As the number of columns in the table increases, or the browser width decreases, the thumbnails reach a point where they start to shrink, and soon disappear entirely. This is not a problem with responsiveness, per se, because it doesn't depend on an absolute browser width. Instead it depends on how wide the table is.

**Comment by dstopp** [comment]
in addition, the height needs to maintain a consistent height so all rows in the table are the same, see 
nh-mvic-mcXXXXXX for examples of height variations.  Consistent height is important for infinite scroll.
