### ISSUE TITLE
Select Metadata "Discard Changes" can corrupt metadata columns

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#967]
The current code for "Discard Changes" in the "Select Metadata" dialog erases the current columns then adds them back one at a time. The problem is that as they are being added back, the "qualified labels" to add to the right-hand column in the UI are taken from the DOM of the current search menu. But those labels aren't necessarily in the DOM anymore if the categories have changed since they were added. 

For example:
- Select Mission = Cassini
- Go to Select Metadata
- Select a field from Cassini Constraints
- Go back and remove Mission = Cassini so that Cassini Constraints goes away
- Go to Select Metadata
- Select Discard Changes
- Open Select Metadata again
- You will see "undefined" where the Cassini field was

**Comment by dstopp** [comment]
note:  save the DOM instead of slugs so the discard works
